function write(filename, mesh, options)
% WRITE  Write an STL surface mesh. Mirrors meshio.stl._stl.write.
%   meshio.stl.write(filename, mesh)              % ASCII (default)
%   meshio.stl.write(filename, mesh, binary=true) % binary
    arguments
        filename
        mesh           (1,1) meshio.Mesh
        options.binary (1,1) logical     = false
    end

    types = strings(1, numel(mesh.cells));
    for i = 1:numel(mesh.cells)
        types(i) = mesh.cells(i).type;
    end
    if ~any(types == "triangle")
        warning("meshio:stl:noTriangles", ...
            "STL can only write triangle cells. No triangle cells found.");
    end
    if numel(mesh.cells) > 1
        invalid = unique(types(types ~= "triangle"));
        if ~isempty(invalid)
            warning("meshio:stl:discardNonTriangle", ...
                "STL can only write triangle cells. Discarding %s.", ...
                strjoin(invalid, ", "));
        end
    end

    if size(mesh.points, 2) == 2
        warning("meshio:stl:pad2D", ...
            "STL requires 3D points, but 2D points given. Appending 0 third component.");
        points = [mesh.points, zeros(size(mesh.points, 1), 1)];
    else
        points = mesh.points;
    end

    tri = mesh.get_cells_type("triangle");
    N = size(tri, 1);
    pts = zeros(N, 3, 3);
    for k = 1:3
        pts(:, :, k) = reshape(points(tri(:), k), N, 3);
    end

    if isKey(mesh.cell_data, "facet_normals")
        normals = mesh.get_cell_data("facet_normals", "triangle");
    else
        v1 = squeeze(pts(:, 2, :) - pts(:, 1, :));
        v2 = squeeze(pts(:, 3, :) - pts(:, 1, :));
        if N == 1   % squeeze of 1x1x3 gives a column; reshape back to row
            v1 = v1(:).';
            v2 = v2(:).';
        end
        normals = cross(v1, v2, 2);
        nrm = sqrt(sum(normals.^2, 2));
        normals = normals ./ nrm;
    end

    if options.binary
        write_binary(filename, pts, normals);
    else
        write_ascii(filename, pts, normals);
    end
end


function write_ascii(filename, pts, normals)
    fid = fopen(filename, 'w');
    if fid < 0
        error("meshio:WriteError", "Cannot open '%s' for writing.", filename);
    end
    cleanup = onCleanup(@() fclose(fid)); %#ok<NASGU>

    fprintf(fid, "solid\n");
    N = size(pts, 1);
    for k = 1:N
        fprintf(fid, "facet normal %.17g %.17g %.17g\n", normals(k, :));
        fprintf(fid, " outer loop\n");
        fprintf(fid, "  vertex %.17g %.17g %.17g\n", squeeze(pts(k, 1, :)));
        fprintf(fid, "  vertex %.17g %.17g %.17g\n", squeeze(pts(k, 2, :)));
        fprintf(fid, "  vertex %.17g %.17g %.17g\n", squeeze(pts(k, 3, :)));
        fprintf(fid, " endloop\nendfacet\n");
    end
    fprintf(fid, "endsolid\n");
end


function write_binary(filename, pts, normals)
    fid = fopen(filename, 'w', 'ieee-le');
    if fid < 0
        error("meshio:WriteError", "Cannot open '%s' for writing.", filename);
    end
    cleanup = onCleanup(@() fclose(fid)); %#ok<NASGU>

    % 80-character header padded with X, ending in newline (matches Python).
    msg = 'This file was generated by meshio (matlab port).';
    msg = [msg, repmat('X', 1, 79 - numel(msg)), newline];
    fwrite(fid, msg, 'uchar');

    N = size(pts, 1);
    fwrite(fid, N, 'uint32');

    % Pack each record as: 3 float32 normal, 9 float32 vertices, 1 uint16 attr.
    % Build a byte buffer all at once for speed.
    normal_bytes = typecast(single(reshape(normals.', [], 1)), 'uint8');  % 12*N bytes
    % pts is Nx3x3 (facet, vertex, coord). Need 9 float32 per facet in order:
    % v1x v1y v1z v2x v2y v2z v3x v3y v3z, repeated per facet.
    pts_perm = permute(pts, [3 2 1]);  % 3x3xN  (coord, vertex, facet)
    pts_flat = single(pts_perm(:));    % 9*N float32 in correct order
    vertex_bytes = typecast(pts_flat, 'uint8');
    attr_bytes = zeros(2 * N, 1, 'uint8');

    normal_bytes = reshape(normal_bytes, 12, N);
    vertex_bytes = reshape(vertex_bytes, 36, N);
    attr_bytes   = reshape(attr_bytes,    2, N);
    record_bytes = [normal_bytes; vertex_bytes; attr_bytes];  % 50 x N
    fwrite(fid, record_bytes, 'uint8');
end
