classdef test_gmsh < helpers.IOTestCase
    % TEST_GMSH  Mirrors meshio/tests/test_gmsh.py.

    properties (TestParameter)
        mesh_v22 = struct( ...
            line       = @helpers.line_mesh, ...
            tri        = @helpers.tri_mesh, ...
            triangle6  = @helpers.triangle6_mesh, ...
            quad       = @helpers.quad_mesh, ...
            quad8      = @helpers.quad8_mesh, ...
            tet        = @helpers.tet_mesh, ...
            tet10      = @helpers.tet10_mesh, ...
            hex        = @helpers.hex_mesh, ...
            hex20      = @helpers.hex20_mesh, ...
            tri_pd1    = @() helpers.add_point_data(helpers.tri_mesh, 1), ...
            tri_pd3    = @() helpers.add_point_data(helpers.tri_mesh, 3), ...
            tri_pd9    = @() helpers.add_point_data(helpers.tri_mesh, 9), ...
            tri_cd1    = @() helpers.add_cell_data(helpers.tri_mesh,  {{"a", [],  "double"}}), ...
            tri_cd3    = @() helpers.add_cell_data(helpers.tri_mesh,  {{"a", 3,   "double"}}), ...
            tri_cd9    = @() helpers.add_cell_data(helpers.tri_mesh,  {{"a", 9,   "double"}}), ...
            tri_fd     = @() helpers.add_field_data(helpers.tri_mesh, [1, 2], "int32"), ...
            tet_fd     = @() helpers.add_field_data(helpers.tet_mesh, [1, 3], "int32"), ...
            hex_fd     = @() helpers.add_field_data(helpers.hex_mesh, [1, 3], "int32"), ...
            periodic   = @gmsh_periodic)

        % v4 excludes line_mesh per Python test_gmsh40.
        mesh_v40 = struct( ...
            tri        = @helpers.tri_mesh, ...
            triangle6  = @helpers.triangle6_mesh, ...
            quad       = @helpers.quad_mesh, ...
            quad8      = @helpers.quad8_mesh, ...
            tet        = @helpers.tet_mesh, ...
            tet10      = @helpers.tet10_mesh, ...
            hex        = @helpers.hex_mesh, ...
            hex20      = @helpers.hex20_mesh, ...
            tri_pd1    = @() helpers.add_point_data(helpers.tri_mesh, 1), ...
            tri_pd3    = @() helpers.add_point_data(helpers.tri_mesh, 3), ...
            tri_pd9    = @() helpers.add_point_data(helpers.tri_mesh, 9), ...
            tri_cd1    = @() helpers.add_cell_data(helpers.tri_mesh,  {{"a", [],  "double"}}), ...
            tri_cd3    = @() helpers.add_cell_data(helpers.tri_mesh,  {{"a", 3,   "double"}}), ...
            tri_cd9    = @() helpers.add_cell_data(helpers.tri_mesh,  {{"a", 9,   "double"}}), ...
            tri_fd     = @() helpers.add_field_data(helpers.tri_mesh, [1, 2], "int32"), ...
            tet_fd     = @() helpers.add_field_data(helpers.tet_mesh, [1, 3], "int32"), ...
            hex_fd     = @() helpers.add_field_data(helpers.hex_mesh, [1, 3], "int32"))

        binary = struct(ascii = false, binary = true)

        reference_v22 = struct( ...
            insulated = struct( ...
                filename      = "insulated-2.2.msh", ...
                ref_sum       = 2.001762136876221, ...
                ref_num_cells = [21, 111]))

        reference_v41 = struct( ...
            insulated = struct( ...
                filename               = "insulated-4.1.msh", ...
                ref_sum                = 2.001762136876221, ...
                ref_num_cells          = struct(line = 21,  triangle = 111), ...
                ref_num_cells_in_sets  = struct(line = 27,  triangle = 120)))
    end

    methods (TestMethodSetup)
        function suppress_expected_warnings(testCase)
            % gmsh writes emit a zero-tag warning for meshes without
            % gmsh:physical / gmsh:geometrical cell data (as does Python meshio);
            % expected during the round-trip tests, so keep it out of the log.
            testCase.applyFixture(matlab.unittest.fixtures.SuppressedWarningsFixture( ...
                "meshio:gmsh:zeroTags"));
        end
    end

    methods (Test)
        function test_gmsh22(testCase, mesh_v22, binary)
            writer = @(p, m) meshio.gmsh.write(p, m, ...
                fmt_version = "2.2", binary = binary);
            helpers.write_read(testCase.TmpDir, ...
                writer, @meshio.gmsh.read, mesh_v22(), 1.0e-15);
        end

        function test_gmsh40(testCase, mesh_v40, binary)
            writer = @(p, m) meshio.gmsh.write(p, m, ...
                fmt_version = "4.0", binary = binary);
            helpers.write_read(testCase.TmpDir, ...
                writer, @meshio.gmsh.read, mesh_v40(), 1.0e-15);
        end

        function test_gmsh41(testCase, mesh_v40, binary)
            % v41 takes the same fixture set as v40.
            writer = @(p, m) meshio.gmsh.write(p, m, ...
                fmt_version = "4.1", binary = binary);
            helpers.write_read(testCase.TmpDir, ...
                writer, @meshio.gmsh.read, mesh_v40(), 1.0e-15);
        end

        function test_generic_io(testCase)
            helpers.generic_io(fullfile(testCase.TmpDir, "test.msh"));
            % With additional, insignificant suffix:
            helpers.generic_io(fullfile(testCase.TmpDir, "test.0.msh"));
        end

        function test_reference_file(testCase, reference_v22, binary)
            here = fileparts(mfilename('fullpath'));
            filename = fullfile(here, "meshes", "msh", reference_v22.filename);
            mesh = meshio.read(filename);
            tol = 1.0e-2;
            s = sum(mesh.points, "all");
            testCase.assertTrue( ...
                abs(s - reference_v22.ref_sum) < tol * reference_v22.ref_sum);
            types = strings(1, numel(mesh.cells));
            for i = 1:numel(mesh.cells), types(i) = mesh.cells(i).type; end
            testCase.assertEqual(types, ["line", "triangle"]);
            nperblock = arrayfun(@(c) size(c.data, 1), mesh.cells);
            testCase.assertEqual(nperblock, reference_v22.ref_num_cells);
            geom = mesh.cell_data{"gmsh:geometrical"};
            phys = mesh.cell_data{"gmsh:physical"};
            testCase.assertEqual([numel(geom{1}), numel(geom{2})], reference_v22.ref_num_cells);
            testCase.assertEqual([numel(phys{1}), numel(phys{2})], reference_v22.ref_num_cells);

            writer = @(p, m) meshio.gmsh.write(p, m, ...
                fmt_version = "2.2", binary = binary);
            helpers.write_read(testCase.TmpDir, ...
                writer, @meshio.gmsh.read, mesh, 1.0e-15);
        end

        function test_reference_file_with_entities(testCase, reference_v41, binary)
            here = fileparts(mfilename('fullpath'));
            filename = fullfile(here, "meshes", "msh", reference_v41.filename);
            mesh = meshio.read(filename);
            tol = 1.0e-2;
            s = sum(mesh.points, "all");
            testCase.assertTrue( ...
                abs(s - reference_v41.ref_sum) < tol * reference_v41.ref_sum);

            cd = mesh.cells_dict;
            ref_nc = reference_v41.ref_num_cells;
            testCase.assertEqual(size(cd{"line"},     1), ref_nc.line);
            testCase.assertEqual(size(cd{"triangle"}, 1), ref_nc.triangle);

            phys_dict = mesh.cell_data_dict{"gmsh:physical"};
            testCase.assertEqual(numel(phys_dict{"line"}),     ref_nc.line);
            testCase.assertEqual(numel(phys_dict{"triangle"}), ref_nc.triangle);

            % Note that testing on number of cells in cell_sets_dict will count
            % both cells associated with physical tags, and bounding entities.
            csd = mesh.cell_sets_dict;
            num_line = 0; num_tri = 0;
            sk = keys(csd);
            for i = 1:numel(sk)
                sub = csd{sk(i)};
                if isKey(sub, "line"),     num_line = num_line + numel(sub{"line"});     end
                if isKey(sub, "triangle"), num_tri  = num_tri  + numel(sub{"triangle"}); end
            end
            ref_sets = reference_v41.ref_num_cells_in_sets;
            testCase.assertEqual(num_line, ref_sets.line);
            testCase.assertEqual(num_tri,  ref_sets.triangle);

            writer = @(p, m) meshio.gmsh.write(p, m, ...
                fmt_version = "4.1", binary = binary);
            helpers.write_read(testCase.TmpDir, ...
                writer, @meshio.gmsh.read, mesh, 1.0e-15);
        end
    end
end


function mesh = gmsh_periodic()
    mesh = helpers.quad_mesh();
    trns = zeros(1, 16);   % just for io testing
    mesh.gmsh_periodic = { ...
        {0, [3, 1], [],   [2 0]}, ...
        {0, [4, 6], [],   [3 5]}, ...
        {1, [2, 1], trns, [5 0; 4 1; 4 2]}};
end
