classdef test_ply < helpers.IOTestCase
    % TEST_PLY  Mirrors meshio/tests/test_ply.py.

    properties (TestParameter)
        mesh_fixture = struct( ...
            tri          = @helpers.tri_mesh, ...
            quad         = @helpers.quad_mesh, ...
            tri_quad     = @helpers.tri_quad_mesh, ...
            tri_pd_int   = @() helpers.add_point_data(helpers.tri_mesh, 1, dtype="int32"), ...
            tri_pd_float = @() helpers.add_point_data(helpers.tri_mesh, 1, dtype="double"), ...
            line         = @helpers.line_mesh, ...
            polygon      = @helpers.polygon_mesh)

        binary = struct(ascii=false, binary=true)

        reference_case = struct( ...
            bunny = struct( ...
                filename      = "bun_zipper_res4.ply", ...
                ref_sum       = 3.414583969116211e+01, ...
                ref_num_cells = 948), ...
            tet = struct( ...
                filename      = "tet.ply", ...
                ref_sum       = 6, ...
                ref_num_cells = 4))
    end

    methods (Test)
        function test_io(testCase, mesh_fixture, binary)
            mesh = mesh_fixture();
            for k = 1:numel(mesh.cells)
                c = mesh.cells(k);
                mesh.cells(k) = meshio.CellBlock(c.type, int32(c.data));
            end
            writer = @(p, m) meshio.ply.write(p, m, binary=binary);
            helpers.write_read(testCase.TmpDir, ...
                writer, @meshio.ply.read, mesh, 1.0e-12);
        end

        function test_reference_file(testCase, reference_case)
            here = fileparts(mfilename('fullpath'));
            filename = fullfile(here, "meshes", "ply", reference_case.filename);

            mesh = meshio.read(filename);
            tol = 1.0e-2;
            s = sum(mesh.points, "all");
            testCase.assertTrue(abs(s - reference_case.ref_sum) < tol * abs(reference_case.ref_sum));
            testCase.assertEqual( ...
                size(mesh.get_cells_type("triangle"), 1), reference_case.ref_num_cells);
        end
    end
end
