function write(filename, mesh, options)
% WRITE  Write a Netgen .vol or .vol.gz file.
%   Mirrors meshio.netgen._netgen.write.
    arguments
        filename
        mesh (1,1) meshio.Mesh
        options.float_fmt (1,1) string = ".16e"
    end

    if endsWith(string(filename), ".vol.gz")
        % Write to a temp .vol and gzip-replace.
        tmp_vol = [tempname, '.vol'];
        cleanup_tmp = onCleanup(@() delete(tmp_vol)); %#ok<NASGU>
        fid = fopen(tmp_vol, 'w');
        if fid < 0
            error("meshio:WriteError", "Cannot open temp '%s' for writing.", tmp_vol);
        end
        cleanup = onCleanup(@() fclose(fid)); %#ok<NASGU>
        write_buffer(fid, mesh, options.float_fmt);
        clear cleanup
        gzipped = gzip(tmp_vol);
        movefile(gzipped{1}, char(filename));
        return
    end

    fid = fopen(filename, 'w');
    if fid < 0
        error("meshio:WriteError", "Cannot open '%s' for writing.", filename);
    end
    cleanup = onCleanup(@() fclose(fid)); %#ok<NASGU>
    write_buffer(fid, mesh, options.float_fmt);
end


function write_buffer(fid, mesh, float_fmt)
    [~, dimension] = size(mesh.points);
    cells_per_dim = zeros(1, 4);

    % Netgen can store one cell_index, i.e., integer cell data. Pick one in
    % mesh.cell_data, and prefer "netgen:index" if present. Unfortunately,
    % netgen cannot store the name of the data; when reading, it will always
    % be "netgen:index".
    % See also <https://github.com/nschloe/meshio/issues/1199>.
    if isKey(mesh.cell_data, "netgen:index")
        cells_index = mesh.cell_data{"netgen:index"};
    else
        cells_index = {};
        ck = keys(mesh.cell_data);
        for i = 1:numel(ck)
            v = mesh.cell_data{ck(i)};
            if ~isempty(v) && isinteger(v{1})
                cells_index = v;
                break
            end
        end
        if isempty(cells_index)
            cells_index = repmat({[]}, 1, numel(mesh.cells));
        end
    end

    for i = 1:numel(mesh.cells)
        cells_per_dim(mesh.cells(i).dim + 1) = ...
            cells_per_dim(mesh.cells(i).dim + 1) + size(mesh.cells(i).data, 1);
    end

    fprintf(fid, "# Generated by meshio (matlab port)\n");
    fprintf(fid, "mesh3d\n\n");

    fprintf(fid, "dimension\n%d\n\n", dimension);
    fprintf(fid, "geomtype\n0\n");

    fprintf(fid, "\n# surfnr    bcnr   domin  domout      np      p1      p2      p3\n");
    fprintf(fid, "surfaceelements\n%d\n", cells_per_dim(3));
    for ci = 1:numel(mesh.cells)
        if mesh.cells(ci).dim == 2
            write_cells(fid, mesh.cells(ci), cells_index{ci});
        end
    end

    fprintf(fid, "\n#  matnr      np      p1      p2      p3      p4\n");
    fprintf(fid, "volumeelements\n%d\n", cells_per_dim(4));
    for ci = 1:numel(mesh.cells)
        if mesh.cells(ci).dim == 3
            write_cells(fid, mesh.cells(ci), cells_index{ci});
        end
    end

    fprintf(fid, "\n# surfid  0   p1   p2   trignum1    trignum2   domin/surfnr1    domout/surfnr2   ednr1   dist1   ednr2   dist2\n");
    fprintf(fid, "edgesegmentsgi2\n%d\n", cells_per_dim(2));
    for ci = 1:numel(mesh.cells)
        if mesh.cells(ci).dim == 1
            write_cells(fid, mesh.cells(ci), cells_index{ci});
        end
    end

    fprintf(fid, "\n#          X             Y             Z\n");
    fprintf(fid, "points\n%d\n", size(mesh.points, 1));
    pts = mesh.points;
    if dimension ~= 3
        pts = [pts, zeros(size(pts, 1), 3 - dimension)];
    end
    fmt = ['%', char(float_fmt), repmat([' %', char(float_fmt)], 1, 2), '\n'];
    fprintf(fid, fmt, pts');

    fprintf(fid, "\n#          pnum             index\n");
    fprintf(fid, "pointelements\n%d\n", cells_per_dim(1));
    for ci = 1:numel(mesh.cells)
        if mesh.cells(ci).dim == 0
            write_cells(fid, mesh.cells(ci), cells_index{ci});
        end
    end

    % identifications (optional, from mesh.info)
    if isa(mesh.info, 'dictionary') && isKey(mesh.info, "netgen:identifications") ...
            && isKey(mesh.info, "netgen:identificationtypes")
        ids   = mesh.info{"netgen:identifications"};
        itype = mesh.info{"netgen:identificationtypes"};
        if ~isempty(ids) && ~isempty(itype)
            fprintf(fid, "\nidentifications\n%d\n", size(ids, 1));
            fprintf(fid, "%d %d %d\n", ids');
            fprintf(fid, "\nidentificationtypes\n%d\n", numel(itype));
            fprintf(fid, [repmat('%d ', 1, numel(itype)), '\n'], itype);
        end
    end

    for codim = 0:dimension
        write_codim_domain_data(fid, mesh, cells_index, dimension, codim);
    end

    fprintf(fid, "\nendmesh\n");
end


function write_cells(fid, cell_block, index)
    if size(cell_block.data, 1) == 0
        return
    end
    pmap = meshio.netgen.common.meshio_to_netgen_pmap();
    p = pmap{cell_block.type};
    post_data = [];
    pre_data = [];
    i_index = 1;
    if cell_block.dim == 0
        post_data = 1;
        i_index = 2;
    elseif cell_block.dim == 1
        pre_data = [1, 0];
        post_data = [-1, -1, 0, 0, 1, 0, 1, 0];
    elseif cell_block.dim == 2
        pre_data = [1, 1, 0, 0, numel(p)];
        i_index = 2;
    elseif cell_block.dim == 3
        pre_data = [1, numel(p)];
    else
        error("meshio:WriteError", "Invalid cell dimension: %d", cell_block.dim);
    end

    n = size(cell_block.data, 1);
    col1 = numel(pre_data);
    col2 = col1 + numel(p);
    col3 = col2 + numel(post_data);

    pi = zeros(n, col3, 'int32');
    if col1 > 0
        pi(:, 1:col1) = repmat(int32(pre_data), n, 1);
    end
    % Netgen and MATLAB are both 1-based; just apply the permutation.
    pi(:, col1+1:col2) = int32(cell_block.data(:, p));
    if numel(post_data) > 0
        pi(:, col2+1:col3) = repmat(int32(post_data), n, 1);
    end
    if ~isempty(index)
        pi(:, i_index) = int32(index);
    end

    fmt = [repmat('%d ', 1, col3 - 1), '%d\n'];
    fprintf(fid, fmt, pi');
end


function write_codim_domain_data(fid, mesh, cells_index, dim, codim)
    % assume format as read from gmsh 4.1 files
    data = configureDictionary("int32", "string");
    fk = keys(mesh.field_data);
    for i = 1:numel(fk)
        val = mesh.field_data{fk(i)};
        if numel(val) >= 2 && val(2) == dim - codim
            data(int32(val(1))) = fk(i);
        end
    end

    % set generic default names
    if numEntries(data) == 0
        indices = [];
        for ci = 1:numel(mesh.cells)
            if mesh.cells(ci).dim ~= dim - codim, continue, end
            if isempty(cells_index{ci}), continue, end
            indices = unique([indices; double(cells_index{ci}(:))]);
        end
        for k = 1:numel(indices)
            idx = int32(indices(k));
            data(idx) = sprintf("cd%d_%d", codim, idx);
        end
    end

    if numEntries(data) == 0
        return
    end

    codim_tags = configureDictionary("double", "string");
    codim_tags(0) = "materials";
    codim_tags(1) = "bcnames";
    codim_tags(2) = "cd2names";
    codim_tags(3) = "cd3names";
    fprintf(fid, "\n%s\n", codim_tags(codim));

    ncd = max(double(keys(data)));
    fprintf(fid, "%d\n", ncd);
    for idx = 1:ncd
        if isKey(data, int32(idx))
            fprintf(fid, "%d %s\n", idx, data(int32(idx)));
        else
            fprintf(fid, "%d \n", idx);
        end
    end
end
